version: "3.9"
services:
  backend:
    build: . 
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db3_custom
  db3_custom:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ambassador3_custom
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - .dbdata_custom:/var_custom/lib/mysql
    ports:
      - 3306:3306